### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by jwilner**

### CODE REVIEW

**Comment by jwilner** [comment]
I need to update HEAD in my fork but y'all could just squash merge this. Or just enable dependabot yourselves :trollface:

**Comment by riwsky** [comment]
How was Italy?

**Comment by jwilner** [comment]
Sunny, carby, Italian. It was a good time. Let's do drinks soon. Maybe just
limoncello.

**Comment by riwsky** [comment]
Maybe if there's another freakishly-warm day we can justify busting out an
aperol spritz

**Comment by SoryRawyer** [comment]
Sounds nice

**Review by SoryRawyer — APPROVED** [review]
lgtm

**Pull request merged**
